services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      DATABASE_CONNECTION_STRING: postgres://postgres:postgres@database:5432/database?connect_timeout=300
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - '${HOST_PORT}:5432'
